flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- StateVar-1.1.0.4
- adjunctions-4.3
- base-orphans-0.6
- bifunctors-5.4.2
- binary-0.9.0.0
- comonad-5.0.1
- containers-0.5.10.2
- contravariant-1.4
- distributive-0.5.2
- exceptions-0.8.3
- fail-4.9.0.0
- free-4.12.4
- hashable-1.2.6.0
- intervals-0.8
- kan-extensions-5.0.2
- lens-4.15.2
- logict-0.6.0.2
- mtl-2.2.1
- parallel-3.2.1.1
- prelude-extras-0.4.0.3
- primitive-0.6.2.0
- profunctors-5.2
- random-1.1
- reflection-2.1.2
- semigroupoids-5.2
- semigroups-0.18.3
- stm-2.4.4.1
- tagged-0.8.5
- text-1.2.2.1
- transformers-compat-0.5.1.4
- unordered-containers-0.2.8.0
- vector-0.12.0.1
- void-0.7.2
resolver: ghc-8
